### ISSUE TITLE
Suggestion Upload the mini maps to the wiki

### ISSUE THREAD

**Issue by tigersmith12** [Tonkatunk/Mabi-Pro-Lazyfae-Mods#4]
the wiki has outdated maps. your maps are the only ones that have decent markings.
took a while to find your work and would help tons if added to the wiki

**Comment by Tonkatunk** [comment]
Assume you mean live Mabi's wiki. I won't bother with that for several of my own reasons.
If there's finally an active wiki for Pro, I know nothing about it and the time investment I'd prefer to take for being involved in that is not appealing to me atm.

If someone wishes to take these maps to share or post somewhere else, feel free. Part of the reason I have this github plus readme is to give easy and clear access to the stuff I used/worked on when I'm not playing, as is the case right now.

I do wish to say that if any of these maps are shared, please give proper credits where they are due. I remember putting a little work on some of Pro's custom content, editing them into maps. But almost all the edits from live's mods/version, are ripped from UOTiara and I might have made a few tweaks/additions. Think I added a few marking for treasures directly around Cor village for example, but it would probably be indistinguishable from UOTiara without me mentioning that. I credited kaydee for efforts made on Viridius cave. I don't remember if I added any names directly to the maps, kind of as a signature, to credit other efforts as well. Again, I would encourage sharing of my content, just please double check contributions and sources to ensure proper people get credited and I'm not given undeserved recognition on things.

**Comment by tigersmith12** [comment]
Thank you It’s great to hear that you’re open to others sharing your maps, and I appreciate your emphasis on giving proper credit where it’s due.
